name: Demo Workflow
on: [push]
jobs:
    github-job-demo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "It's working!"
            - run: echo "Step 2"
            - run: echo ${{ github.actor }} is testing actions
            - run: echo Trigger ${{ github.event_name }}
            - run: echo OS ${{ runner.os }}
            - name: Checkout/clone repo code to runner
              uses: actions/checkout@4
            - run: ls ${{ github.workspace }}