name: Deploy to EC2 Workflow
on: [push]
jobs:
    github-job-demo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Copy HTML to EC2 instance
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ec2-user
                key: ${{ secrets.DEPLOY_KEY }}
                port: 22
                source: "index.html"
                target: "/usr/share/nginx/html"